"""
Generate version_info.txt for PyInstaller from src/tag_writer/constants.py.

Run before building:
    python generate_version_info.py

Output: version_info.txt (referenced by tag-writer.spec EXE version= parameter)
"""

import re
import sys
from pathlib import Path

# Read version fields from constants.py
constants_text = Path("src/tag_writer/constants.py").read_text(encoding="utf-8")

def _get(name):
    m = re.search(rf'{name}\s*=\s*"([^"]+)"', constants_text)
    if not m:
        print(f"ERROR: {name} not found in constants.py")
        sys.exit(1)
    return m.group(1)

version_str = _get("APP_VERSION")
app_name    = _get("APP_NAME")
company     = _get("APP_ORGANIZATION")

# Parse version into 4-tuple, stripping any trailing alpha suffix (e.g. "0.2.4a" -> (0,2,4,0))
numeric = re.sub(r'[^\d.]', '', version_str)
parts = [int(x) for x in numeric.split(".") if x]
while len(parts) < 4:
    parts.append(0)
v = tuple(parts[:4])

copyright_str = f"Copyright (c) 2024-2026 {company}"

content = f"""\
# Generated by generate_version_info.py — do not edit by hand.
# Rebuild with: python generate_version_info.py
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={v},
    prodvers={v},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        u'040904B0',
        [StringStruct(u'CompanyName', u'{company}'),
         StringStruct(u'FileDescription', u'{app_name}'),
         StringStruct(u'FileVersion', u'{version_str}'),
         StringStruct(u'InternalName', u'tag-writer'),
         StringStruct(u'LegalCopyright', u'{copyright_str}'),
         StringStruct(u'OriginalFilename', u'tag-writer.exe'),
         StringStruct(u'ProductName', u'{app_name}'),
         StringStruct(u'ProductVersion', u'{version_str}')])
    ]),
    VarFileInfo([VarStruct(u'Translation', [0x0409, 1200])])
  ]
)
"""

Path("version_info.txt").write_text(content, encoding="utf-8")
print(f"version_info.txt written for {app_name} v{version_str}")
